export const SET_USER = 'SET_USER';
export const SET_USER_REPOS = 'SET_USER_REPOS';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const REMOVE_ACCESS_TOKEN = 'REMOVE_ACCESS_TOKEN';
export const REMOVE_USER = 'REMOVE_USER';
export const AUTHENTICATED = 'AUTHENTICATED';
export const INIT_SESSION = 'INIT_SESSION';
export const SET_USER_REPOS = 'SET_USER_REPOS';